### ISSUE TITLE
ArgumentOutOfRangeException thrown after connecting

### ISSUE THREAD

**Issue by Brominarium** [Niewiarowski/HabboInterceptor#1]
When connecting to the Dutch Habbo Hotel (habbo.nl) it's stuck loading on 76%. It also throws an ArgumentOutOfRangeException:
<pre>
[08/12/2019 21:42:56] Connected.
-> {l:50}{h:4000}: [0]!PRODUCTION-201911262207-778945893[0][5]FLASH[0][0][0][1][0][0][0][0]
[08/12/2019 21:42:56] An exception was thrown during packet interception:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
   at Interceptor.Communication.Packet.ConstructTo(Span`1 finalPacket) in D:\Repositories\HabboInterceptor\Interceptor\Communication\Packet.cs:line 121
   at Interceptor.Communication.Packet.ConstructTo(Memory`1 finalPacket) in D:\Repositories\HabboInterceptor\Interceptor\Communication\Packet.cs:line 111
   at Interceptor.HabboInterceptor.SendInternalAsync(TcpClient client, Packet packet, Boolean created) in D:\Repositories\HabboInterceptor\Interceptor\HabboInterceptor.cs:line 353
   at Interceptor.HabboInterceptor.InterceptAsync(TcpClient client, TcpClient server) in D:\Repositories\HabboInterceptor\Interceptor\HabboInterceptor.cs:line 491
[08/12/2019 21:42:56] Disconnected.
</pre>

It calls MemoryMarshal.Write() with a packet that looks something like: {l:0} {h:1400}. (Length of 0)

**Comment by Niewiarowski** [comment]
Should be fixed.
